### PR TITLE
Drastically improving syntax highlighting

### PR DESCRIPTION
**Pull request by pjmiravalle**
Hi all!

When v2.0.0 for this extension came out back in 2020, quite a few issues with syntax highlighting surfaced. At the time, I decided to create an [extension of my own](https://marketplace.visualstudio.com/items?itemName=pjmiravalle.terraform-advanced-syntax-highlighting) to address these issues, which ended up having a good amount of success.

Recently, Tony from HashiCorp reached out to me asking if we could bring these fixes on over to the official Terraform extension. I thought that was a great idea, and over the past few days I've been working on polishing this up before bringing it on over to y'all for review.

### Related Issues
The following issues have been tested and fixed:
- #194 
- #197
- #320
- #345 
- #426 
- #486
- #498 
- #509

##### DISCLAIMER
Most of these changes were developed as a side project while going through work crunch, planning a wedding, and moving across the country. I apologize in advance for the lack of documentation! :)

### CODE REVIEW

**Comment by Shocktrooper** [comment]
@radeksimko Any thoughts on when this will get reviewed and merged in? pjmiravalle put in a lot of work and it would be a bit of a waste to have this go stale

**Comment by DarthNaul** [comment]
@radeksimko looks like @Shocktrooper got confused and has github account and authors name as two separate entities.

**Comment by Shocktrooper** [comment]
> @radeksimko looks like @Shocktrooper (CLA bot) got confused and has github account and authors name as two separate entities.

Can this be manually fixed then? Also I am not a bot

**Comment by DarthNaul** [comment]
guess bot's aren't the only ones that get confused sorry @Shocktrooper

**Pull request closed without merging**
