### PR TITLE
Switch to GitHub issue form templates

### PR DESCRIPTION
**Pull request by xiehan**
I was chatting with @dbanck the other day and mentioned that since we switched to these templates on the CDK team, one nice side effect has been that we're seeing more contributions from the community thanks to the "Help Wanted" section. They've also generally resulted in issues that are more readable and actionable for us.

Feedback welcome, I'm happy to continue to tweak. I think the biggest thing to think about is what fields should be required vs. optional; ideally we'd avoid having 15 required fields for users to fill out because we don't want to discourage anyone from filing an issue.

If you haven't worked with issue templates before, one thing to note is that it's impossible (AFAIK) to preview the resulting forms in any way without first merging the code. So if you think this is "close enough" and you'd like to see it in action, we can also merge this PR, view the forms, and then open a new PR with additional tweaks.

### CODE REVIEW

**Review by jpogran — APPROVED** [review]
I think this is a great start!

**Review by dbanck — CHANGES_REQUESTED** [review]
Merging this will probably break the `Generate Bug Report' command in VS Code, as it disables the creation of plain text issues.

[Example URL generated from that command](https://github.com/hashicorp/vscode-terraform/issues/new?body=Issue%20Description%0A=====%0A%0Atest%0A%0AEnvironment%20Information%0A=====%0A%0ATerraform%20Information%0A-----%0A%0A%0AVersion:%091.4.6%0APlatform:%09darwin_arm64%0AOutdated:%09false%0A%20%20%20%20%0A%0AVisual%20Studio%20Code%0A-----%0A%0A%7C%20Name%20%7C%20Version%20%7C%0A%7C%20---%20%7C%20---%20%7C%0A%7C%20Operating%20System%20%7C%20Darwin%20arm64%2022.5.0%20%7C%0A%7C%20VSCode%20%7C%201.78.2%7C%0A%0AVisual%20Studio%20Code%20Extensions%0A-----%0A%0A%3Cdetails%3E%3Csummary%3EVisual%20Studio%20Code%20Extensions(Click%20to%20Expand)%3C/summary%3E%0A%0A%7CExtension%7CAuthor%7CVersion%7C%0A%7C---%7C---%7C---%7C%0A%7Cesbuild-problem-matchers%7Cconnor4312%7C0.0.2%7C%0A%7Cgithub-vscode-theme%7CGitHub%7C6.3.4%7C%0A%7Cgo%7Cgolang%7C0.38.0%7C%0A%7Chcl%7Chashicorp%7C0.3.2%7C%0A%7Cruby%7Crebornix%7C0.28.1%7C%0A%7Cterraform%7Chashicorp%7C2.26.1%7C%0A%7Ctest-snapshot-viewer%7Cigress%7C0.0.1%7C%0A%7Cvscode-eslint%7Cdbaeumer%7C2.4.0%7C%0A%7Cvscode-ruby%7Cwingrunr21%7C0.28.0%7C%0A%3C/details%3E%0A%0AExtension%20Logs%0A-----%0A%0A%3E%20Find%20this%20from%20the%20first%20few%20lines%20of%20the%20relevant%20Output%20pane:%0AView%20-%3E%20Output%20-%3E%20%27HashiCorp%20Terraform%27%0A%0A)

**Comment by radeksimko** [comment]
@xiehan I don't see the same config here in this repo, but I thought the main reason it appears to work in CDK, in spite of https://github.com/hashicorp/terraform-cdk/blob/main/.github/ISSUE_TEMPLATE/config.yml#L4 is because we're looking at the repo as someone with elevated privileges? I might be wrong though. It may be worth checking the experience under a GitHub account which is not part of the HashiCorp org, just to confirm.

**Comment by xiehan** [comment]
@radeksimko You all have it set up this way even today though: https://github.com/hashicorp/vscode-terraform/blob/main/.github/ISSUE_TEMPLATE/config.yml#L4 <-- I did not add that, this is already there.

**Comment by dbanck** [comment]
> As proof, [here](https://github.com/hashicorp/terraform-cdk/issues/new?body=Issue%20Description%0A=====%0A%0Atest%0A%0AEnvironment%20Information%0A=====%0A%0ATerraform%20Information%0A-----%0A%0A%0AVersion:%091.4.6%0APlatform:%09darwin_arm64%0AOutdated:%09false%0A%20%20%20%20%0A%0AVisual%20Studio%20Code%0A-----%0A%0A%7C%20Name%20%7C%20Version%20%7C%0A%7C%20---%20%7C%20---%20%7C%0A%7C%20Operating%20System%20%7C%20Darwin%20arm64%2022.5.0%20%7C%0A%7C%20VSCode%20%7C%201.78.2%7C%0A%0AVisual%20Studio%20Code%20Extensions%0A-----%0A%0A%3Cdetails%3E%3Csummary%3EVisual%20Studio%20Code%20Extensions(Click%20to%20Expand)%3C/summary%3E%0A%0A%7CExtension%7CAuthor%7CVersion%7C%0A%7C---%7C---%7C---%7C%0A%7Cesbuild-problem-matchers%7Cconnor4312%7C0.0.2%7C%0A%7Cgithub-vscode-theme%7CGitHub%7C6.3.4%7C%0A%7Cgo%7Cgolang%7C0.38.0%7C%0A%7Chcl%7Chashicorp%7C0.3.2%7C%0A%7Cruby%7Crebornix%7C0.28.1%7C%0A%7Cterraform%7Chashicorp%7C2.26.1%7C%0A%7Ctest-snapshot-viewer%7Cigress%7C0.0.1%7C%0A%7Cvscode-eslint%7Cdbaeumer%7C2.4.0%7C%0A%7Cvscode-ruby%7Cwingrunr21%7C0.28.0%7C%0A%3C/details%3E%0A%0AExtension%20Logs%0A-----%0A%0A%3E%20Find%20this%20from%20the%20first%20few%20lines%20of%20the%20relevant%20Output%20pane:%0AView%20-%3E%20Output%20-%3E%20%27HashiCorp%20Terraform%27%0A%0A)'s your link with `vscode-terraform` replaced with the CDK team's repo (which also uses the issue templates). The link still works anyway.

So the link works for you? For me it always redirects to https://github.com/hashicorp/terraform-cdk/issues/new/choose, so I assumed that plain text issues were disabled.

**Comment by xiehan** [comment]
Interesting, yeah it does work for me. I guess in that case Radek's point is true that it's because I have elevated privileges, but in general I don't think the issue you're pointing out has anything to do with plaintext vs. forms, it's the `blank_issues_enabled` setting which is currently `false` for this repo (I didn't touch that, it's been that way for 2 years), but maybe it should be changed `true`.

**Review by dbanck — APPROVED** [review]
Interesting!

I have confirmed with someone outside of HashiCorp that the `Generate Bug Report` link currently works for this repository.

Will check again after this is merged. Still confused about the setting, tho.

**Pull request merged**
