### PR TITLE
Add workflows for drafting and publishing a release

### PR DESCRIPTION
**Pull request by aeschright**
### Depends on

 - https://github.com/hashicorp/vscode-terraform/pull/773
 - https://github.com/hashicorp/vscode-terraform/pull/776
 - https://github.com/hashicorp/vscode-terraform/pull/777

--- 

This could all be combined into one workflow if we have an automated way to parse the changelog into release notes.

This is pending as a draft until we have the [token](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token) available.

### CODE REVIEW

**Comment by radeksimko** [comment]
Token was added to `Secrets` and I also modified the workflows according to my manual testing in a fork:
https://github.com/radeksimko/vscode-terraform/runs/3608892891

This enables us to cut releases in a single step/workflow.

Changelog in Marketplace entry is sourced automatically from `Changelog.md` anyway. We can continue updating that changelog manually and ensure it's not forgotten via a custom input where a maintainer has to confirm this.

We can also continue copy-pasting the relevant part of changelog into GitHub Release notes.

Lastly we should not need to continue publishing the vsix to GitHub as this encourages a bad practice of users installing released extension outside of Marketplace.

Screenshot 2021-09-15 at 11 41 49

Depends on:

 - https://github.com/hashicorp/vscode-terraform/pull/773
 - https://github.com/hashicorp/vscode-terraform/pull/776
 - https://github.com/hashicorp/vscode-terraform/pull/777

**Comment by jpogran** [comment]
👍🏼 to revisiting automatically creating a Github release, there is alot we can bike shed with that. Ideally we could create the release with a section of our changelog, which would compliment the marketplace display. Right now automating the changelog would be non-trivial, maybe with things like https://github.com/github/roadmap/issues/248 that will be easier.

**Review by jpogran — APPROVED** [review]
:shipit:

**Comment by radeksimko** [comment]
> Ideally we could create the release with a section of our changelog, which would compliment the marketplace display.

FWIW the Marketplace already sources the changelog automatically from `Changelog.md` it appears:
https://marketplace.visualstudio.com/items/HashiCorp.terraform/changelog

**Pull request merged**
