### PR TITLE
Add for expression snippets

### PR DESCRIPTION
**Pull request by reegnz**
Add snippets to for expressions for both maps and lists.

### CODE REVIEW

**Comment by reegnz** [comment]
Example on how the snippets work:

for_list
for_map

**Review by NoseyNick — APPROVED** [review]

**Review by apetalik-cloudera — APPROVED** [review]
LGTM.

**Comment by aeschright** [comment]
Thanks for submitting this! I'd like to keep the tab order on all of the snippets consistent, so it remains in the same order as when someone would be typing out the full text. If you can update that, I'll be happy to approve the PR.

**Comment by reegnz** [comment]
Sure, will fix that it next week.

**Comment by reegnz** [comment]
@aeschright Sorry for the delay, coompletely forgot about this PR. Fixed the tab ordering.

**Comment by radeksimko** [comment]
Hi @reegnz 
Sorry for the delay in reviewing your PR.

Our longer-term plan is to actually remove the existing snippets from the extension and handle this functionality within the language server. The server can provide more contextual completion - e.g. avoid inserting `for ... in ...` to an empty file where it isn't valid, but only to an argument value after `=`.

This functionality is tracked under https://github.com/hashicorp/terraform-ls/issues/527 and is on our near-term roadmap, alongside other expression types as outlined in https://github.com/hashicorp/vscode-terraform/issues/641

With that in mind I'm going to close this PR.

Thank you for your contribution and understanding.

**Pull request closed without merging**
